name: Pixeebot Fix

on:
  check_run:
    types: [ completed ]

permissions:
  id-token: write

jobs:
  pixeebot-fix:
    name: Pixeebot Fix
    if: ${{
      (!contains(github.actor, 'bot') &&
      toJson(github.event.check_run.pull_requests) != '[]' &&
      github.event.check_run.name == 'SonarCloud Code Analysis') ||
      github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: Upload file and trigger analysis
        uses: JesusCotlamee/upload-tool-results-action@273ba8f7f4e77e7176cf0236de38c221763803b0
        with:
          tool: 'sonar'
