name: Pixeebot Fix

on:
  check_run:
    types: [ completed ]

permissions:
  id-token: write

jobs:
  pixeebot-fix:
    name: Pixeebot Fix
    if: ${{ !startsWith(github.actor, 'pixee') && github.event.check_run.name == 'SonarCloud Code Analysis' }}
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upload file and trigger analysis
        uses: JesusCotlamee/pixee-actions/analysis-input@main
        with:
          tool: 'sonar'
          sonar-component-key: fjpgtt_test-sonar-integration-with-app
