name: Upload file and trigger analysis - pull request

on:
  check_run:
    types: [ completed ]

permissions:
  id-token: write

jobs:
  analysis-input:
    runs-on: ubuntu-latest
    if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    name: Upload file and trigger analysis
    timeout-minutes: 6

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: SonarCloud download
        run: |
          PR_NUMBER=${{ join(github.event.check_run.pull_requests.*.number, '') }}
          echo "$PR_NUMBER"
          SENDER = ${{github.event.check_run.sender}}
          
          URL="https://sonarcloud.io/api/issues/search?componentKeys=fjpgtt_test-sonar-integration-with-app&resolved=false"
          
          if [ -n "$PR_NUMBER" ]; then
            URL="${URL}&pullRequest=$PR_NUMBER"
          fi
          echo "$SENDER"
          ANALYSIS_SHA=${{ github.event.check_run.head_sha }}
          echo "$ANALYSIS_SHA"
          
          curl -v "$URL" -o sonar_issues.json
      - name: SonarCloud Upload file and trigger analysis
        uses: JesusCotlamee/pixee-actions/analysis-input@main
        with:
          FILE: 'sonar_issues.json'
          TOOL: 'sonar'
